// importing dependencies
import com.twilio.Twilio;
import com.twilio.rest.api.v2010.account.Message;
import com.twilio.type.PhoneNumber;

// class definition
public class SendSMS {

  // declaring global variables	
  public static final String ACCOUNT_SID = "AC8c941f54f9b3450f5d1d2fd069a55db6";
  
  //  -- you have to create an Twilio account to get auth_token --
  public static final String AUTH_TOKEN = "0e2f7d304ad04c65e2b3c1721c0f5663";

  // declaring constructor
  SendSMS() {
	    // start configurations
	    Twilio.init(ACCOUNT_SID, AUTH_TOKEN);

	    // send message
	    Message message = Message.creator(new PhoneNumber("+YOUR_NUMBER"), // to
	        new PhoneNumber("+15183179461"), // from -- this number is generated by Twilio.com
	        "The fire alert has been activated!!").create(); // message we want to send
	    	
	    // message if message sent successfully.
	    System.out.println("Message sent Successfully.");
  }
}